### ISSUE TITLE
SSE?

### ISSUE THREAD

**Issue by den1k** [wkok/openai-clojure#1]
OpenAI offers SSE to stream results as they come generate. Would be great if this library supported that

**Comment by wkok** [comment]
Thanks for highlighting, I'll see what's involved in supporting it

**Comment by wkok** [comment]
Support for streamed results has been added in the [sse](https://github.com/wkok/openai-clojure/tree/sse) branch

Usage instructions in [Streaming Token Events](https://github.com/wkok/openai-clojure/blob/sse/doc/sse.md)

Feel free to try it out from this branch, will release after adding a couple more tests.

**Comment by den1k** [comment]
Lovely. Thank you!

**Comment by wkok** [comment]
Released in v0.3.0
