### ISSUE TITLE
Expose a way to pass api key instead of env var only?

### ISSUE THREAD

**Issue by benjamin-asdf** [wkok/openai-clojure#10]
Hi, I will for the moment redifine `wkok.openai-clojure.openai/add-headers` because I would like control over how to pass the api key.

**Comment by wkok** [comment]
Hello,

Thanks for the suggestion

In the branch `override-api-key` I've added the ability to (re)initialize the `api-key` and/or `organization` at any time with

```
(wkok.openai-clojure.openai/init {:api-key "xxxxx"})
```

would something like this be sufficient for your use case?

**Comment by benjamin-asdf** [comment]
Hi thanks for checking that out.
I sort of wanted to pass the api-key as parameter. Maybe via optionals in the public functions?
But your suggestion would also already help.

**Comment by wkok** [comment]
Right, this branch now allows for passing the API Key in any of these ways:

1. In the optional `options` arg of each api function
```
(api/create-completion {:model "text-davinci-003"
                        :prompt "Say this is a test"}
                       {:api-key "xxxxx"})
```

2. Or in a once-off global call to
```
(wkok.openai-clojure.openai/init {:api-key "xxxxx"})
```
3. Finally as env var

**Comment by wkok** [comment]
I've removed the global `init` way as it is really redundant now with the options in each api call and made the code unnecessarily complex.  

So the two ways are:

1. In the optional `options` arg of each api function
```
(api/create-completion {:model "text-davinci-003"
                        :prompt "Say this is a test"}
                       {:api-key "xxxxx"})
```

2. Finally as env var

**Comment by benjamin-asdf** [comment]
That's great, thanks

**Comment by wkok** [comment]
Released https://github.com/wkok/openai-clojure/releases/tag/0.5.0
