### ISSUE TITLE
Pass Azure endpoint in options, instead of environment vars

### ISSUE THREAD

**Issue by pguillebert** [wkok/openai-clojure#17]
Hi

I'm using the library with Azure and would like to define the endpoint without having to deal with Env variables.

Any chance we can get something similar to https://github.com/wkok/openai-clojure/issues/10 but for the `AZURE_OPENAI_API_ENDPOINT` ? 

thank you!

**Comment by wkok** [comment]
Hello!

This is now supported in v0.6.0

See: https://cljdoc.org/d/net.clojars.wkok/openai-clojure/0.6.0/doc/usage-azure-openai#options
