### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by blindcoding9** [wkok/openai-clojure#31]
```
Error printing return value (SunCertPathBuilderException) at sun.security.provider.certpath.SunCertPathBuilder/build (SunCertPathBuilder.java:141).
unable to find valid certification path to requested target
```

Using JVM 11 and version 0.9.0 I can't send any request anymore

**Comment by wkok** [comment]
Unable to reproduce. 

The error indicates a problem with client side certificates, have you tried with other (newer) versions of Java?

**Comment by blindcoding9** [comment]
I imported the openai certificate and worked.

Thanks
