### ISSUE TITLE
Support for Speech API

### ISSUE THREAD

**Issue by ovistoica** [wkok/openai-clojure#39]
Thank you for this great library & being active in maintaining it.

I see currently it does not support the [speech API](https://platform.openai.com/docs/api-reference/audio/createSpeech), and my biggest need: [Streaming Speech API](https://platform.openai.com/docs/guides/text-to-speech/streaming-real-time-audio)

Is this planned or development in progress? If not, I would love to contribute with a PR

Let me know how I should proceed, thank you!

**Comment by wkok** [comment]
Released: https://github.com/wkok/openai-clojure/releases/tag/0.13.0
Thanks!
