### ISSUE TITLE
Warning about no matching content-type

### ISSUE THREAD

**Issue by aamedina** [wkok/openai-clojure#42]
Hi,

When I call any OpenAI function for the first time I see the following warning printed:
```
No matching content-type available {:supported-content-types #{application/json application/transit+msgpack application/transit+json application/edn}, :available-content-types (application/octet-stream), :header Content-Type}
```

But everything seems to work normally and the warning isn't printed a second time.

**Comment by wkok** [comment]
Should be safe to ignore, but I'll have a look to see if it can be suppressed or otherwise handled.

Thanks.
