### ISSUE TITLE
Open LLama Compatibility

### ISSUE THREAD

**Issue by markbastian** [wkok/openai-clojure#54]
[Ollama](https://ollama.ai/blog/openai-compatibility) has announced OpenAI API compatibility and the [Llama API](https://www.llama-api.com/) website has [documentation examples](https://docs.llama-api.com/essentials/chat) using the Python OpenAI client. It would be great to see this library work with the Llama API as well.

**Comment by wkok** [comment]
Hello!

We have the ability to override the openai endpoint in options: 
https://cljdoc.org/d/net.clojars.wkok/openai-clojure/0.15.0/doc/usage-openai#options

Maybe it already works?

**Comment by jkreed** [comment]
I can confirm it does work. Here is a snippet I was able to successfully run.

```clojure
(api/create-chat-completion {:model "llama3.1"
                                                  :messages [{:role "user"
                                                              :content "why are my eyes blue?"}]
                                                  :stream true
                                                  :on-next #(prn %)}
                                                 {:api-key "required but unused key"
                                                  :api-endpoint "http://localhost:11434/v1"})
```

**Comment by wkok** [comment]
> I can confirm it works. Here is a snippet I was able to successfully run.

Thanks for confirming!
