### ISSUE TITLE
v0.18.0 is missing `submit-tool-outputs-to-run`

### ISSUE THREAD

**Issue by quackercrumbs** [wkok/openai-clojure#65]
From the 0.18.0 jar, it seems like its gone in `wkok/openai_clojure/api.clj`

If you compare the v0.17.0 docs its present, but its missing in the v.0.18.0 docs

v0.17.0: https://cljdoc.org/d/net.clojars.wkok/openai-clojure/0.17.0/api/wkok.openai-clojure.api
v0.18.0: https://cljdoc.org/d/net.clojars.wkok/openai-clojure/0.18.0/api/wkok.openai-clojure.api

**Comment by wkok** [comment]
Thanks for reporting.

Fixed https://github.com/wkok/openai-clojure/releases/tag/0.18.1
