### ISSUE TITLE
Images using Azure

### ISSUE THREAD

**Issue by HanjoPurebuddha** [wkok/openai-clojure#67]
Hi thank you for the repo. Just confirming that I would need to figure out my own way to do images using my Azure key?

Thanks again

**Comment by wkok** [comment]
Hi there, 

Short answer for now, yes. 

However, I see the [latest Azure OpenAI spec](https://learn.microsoft.com/en-gb/azure/ai-services/openai/reference) do now list images, among other APIs so it should now be possible to add those functions to this library.

**Comment by HanjoPurebuddha** [comment]
Looking forward to it :) I can figure it out in the meantime...

**Comment by wkok** [comment]
[v0.20.0](https://github.com/wkok/openai-clojure/releases/tag/0.20.0) now supports Translations, Transcriptions & Images (create only) as in their GA release.

**Comment by HanjoPurebuddha** [comment]
Wow! Thank you! This was exactly what I needed.
