### ISSUE TITLE
How do you handle request timeout?

### ISSUE THREAD

**Issue by HanjoPurebuddha** [wkok/openai-clojure#69]
Hey thanks so much for the library, I've been using it a ton.

My requests seem to just kind of stall sometimes. Is there a way to submit a timeout after 2 minutes and retry?

**Comment by wkok** [comment]
Apologies for not responding sooner. You've closed the issue already so you're probably sorted, but for completeness we can specify request timeout in the request options, see
 https://cljdoc.org/d/net.clojars.wkok/openai-clojure/0.19.0/doc/usage-azure-openai#request-options

**Comment by HanjoPurebuddha** [comment]
Thanks! This is exactly what I needed.
