### ISSUE TITLE
vector stores

### ISSUE THREAD

**Issue by pdenno** [wkok/openai-clojure#74]
I have experimented with vector stores in your code and found that,  except for retrieve-vector-store, things work as expected, [gist](https://gist.github.com/pdenno/afecebd31ef721710408884945e00b3d). Regarding retrieve-vector-store, I get a "could not find route" error. Perhaps OpenAI realized that we don't really need this function. It seems to me that if you call modify-vector-store with no arguments, it does the same thing. I could do a PR if you'd like, but I'm not sure how your test files work.

**Comment by wkok** [comment]
Hi there!

Please do submit a PR it will be much appreciated!

### retrieve-vector-store

Regarding `retrieve-vector-store` if you keep it like you've got but just change the operation id to `:get-vector-store` that should work, ie. this line:

from:
```clojure
(core/response-for :retrieve-vector-store params opts)
```

to:

```clojure
(core/response-for :get-vector-store params opts)
```

> We try to keep the function names matching the OpenAI headings in the API Reference, ie. Retrieve Vector Store (`:retrieve-vector-store`) even though the actual operation id in their yaml file is `getVectorStore`

### tests

Please add the new functions to `wkok.openai-clojure.api-test/api-test`. Each function call in the test is stubbed to return `:success` when it could successfully parse the request.
